// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package dcvirtualinterfacev3

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-opentelekomcloud.dcVirtualInterfaceV3.DcVirtualInterfaceV3",
		reflect.TypeOf((*DcVirtualInterfaceV3)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "addressFamily", GoGetter: "AddressFamily"},
			_jsii_.MemberProperty{JsiiProperty: "addressFamilyInput", GoGetter: "AddressFamilyInput"},
			_jsii_.MemberProperty{JsiiProperty: "asn", GoGetter: "Asn"},
			_jsii_.MemberProperty{JsiiProperty: "asnInput", GoGetter: "AsnInput"},
			_jsii_.MemberProperty{JsiiProperty: "bandwidth", GoGetter: "Bandwidth"},
			_jsii_.MemberProperty{JsiiProperty: "bandwidthInput", GoGetter: "BandwidthInput"},
			_jsii_.MemberProperty{JsiiProperty: "bgpMd5", GoGetter: "BgpMd5"},
			_jsii_.MemberProperty{JsiiProperty: "bgpMd5Input", GoGetter: "BgpMd5Input"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "createdAt", GoGetter: "CreatedAt"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "description", GoGetter: "Description"},
			_jsii_.MemberProperty{JsiiProperty: "descriptionInput", GoGetter: "DescriptionInput"},
			_jsii_.MemberProperty{JsiiProperty: "deviceId", GoGetter: "DeviceId"},
			_jsii_.MemberProperty{JsiiProperty: "directConnectId", GoGetter: "DirectConnectId"},
			_jsii_.MemberProperty{JsiiProperty: "directConnectIdInput", GoGetter: "DirectConnectIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableBfd", GoGetter: "EnableBfd"},
			_jsii_.MemberProperty{JsiiProperty: "enableBfdInput", GoGetter: "EnableBfdInput"},
			_jsii_.MemberProperty{JsiiProperty: "enableNqa", GoGetter: "EnableNqa"},
			_jsii_.MemberProperty{JsiiProperty: "enableNqaInput", GoGetter: "EnableNqaInput"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lagId", GoGetter: "LagId"},
			_jsii_.MemberProperty{JsiiProperty: "lagIdInput", GoGetter: "LagIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "localGatewayV4Ip", GoGetter: "LocalGatewayV4Ip"},
			_jsii_.MemberProperty{JsiiProperty: "localGatewayV4IpInput", GoGetter: "LocalGatewayV4IpInput"},
			_jsii_.MemberProperty{JsiiProperty: "localGatewayV6Ip", GoGetter: "LocalGatewayV6Ip"},
			_jsii_.MemberProperty{JsiiProperty: "localGatewayV6IpInput", GoGetter: "LocalGatewayV6IpInput"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "region", GoGetter: "Region"},
			_jsii_.MemberProperty{JsiiProperty: "remoteEpGroup", GoGetter: "RemoteEpGroup"},
			_jsii_.MemberProperty{JsiiProperty: "remoteEpGroupInput", GoGetter: "RemoteEpGroupInput"},
			_jsii_.MemberProperty{JsiiProperty: "remoteGatewayV4Ip", GoGetter: "RemoteGatewayV4Ip"},
			_jsii_.MemberProperty{JsiiProperty: "remoteGatewayV4IpInput", GoGetter: "RemoteGatewayV4IpInput"},
			_jsii_.MemberProperty{JsiiProperty: "remoteGatewayV6Ip", GoGetter: "RemoteGatewayV6Ip"},
			_jsii_.MemberProperty{JsiiProperty: "remoteGatewayV6IpInput", GoGetter: "RemoteGatewayV6IpInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetAddressFamily", GoMethod: "ResetAddressFamily"},
			_jsii_.MemberMethod{JsiiMethod: "resetAsn", GoMethod: "ResetAsn"},
			_jsii_.MemberMethod{JsiiMethod: "resetBgpMd5", GoMethod: "ResetBgpMd5"},
			_jsii_.MemberMethod{JsiiMethod: "resetDescription", GoMethod: "ResetDescription"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableBfd", GoMethod: "ResetEnableBfd"},
			_jsii_.MemberMethod{JsiiMethod: "resetEnableNqa", GoMethod: "ResetEnableNqa"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetLagId", GoMethod: "ResetLagId"},
			_jsii_.MemberMethod{JsiiMethod: "resetLocalGatewayV4Ip", GoMethod: "ResetLocalGatewayV4Ip"},
			_jsii_.MemberMethod{JsiiMethod: "resetLocalGatewayV6Ip", GoMethod: "ResetLocalGatewayV6Ip"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetRemoteGatewayV4Ip", GoMethod: "ResetRemoteGatewayV4Ip"},
			_jsii_.MemberMethod{JsiiMethod: "resetRemoteGatewayV6Ip", GoMethod: "ResetRemoteGatewayV6Ip"},
			_jsii_.MemberMethod{JsiiMethod: "resetResourceTenantId", GoMethod: "ResetResourceTenantId"},
			_jsii_.MemberMethod{JsiiMethod: "resetServiceEpGroup", GoMethod: "ResetServiceEpGroup"},
			_jsii_.MemberProperty{JsiiProperty: "resourceTenantId", GoGetter: "ResourceTenantId"},
			_jsii_.MemberProperty{JsiiProperty: "resourceTenantIdInput", GoGetter: "ResourceTenantIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "routeMode", GoGetter: "RouteMode"},
			_jsii_.MemberProperty{JsiiProperty: "routeModeInput", GoGetter: "RouteModeInput"},
			_jsii_.MemberProperty{JsiiProperty: "serviceEpGroup", GoGetter: "ServiceEpGroup"},
			_jsii_.MemberProperty{JsiiProperty: "serviceEpGroupInput", GoGetter: "ServiceEpGroupInput"},
			_jsii_.MemberProperty{JsiiProperty: "status", GoGetter: "Status"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "type", GoGetter: "Type"},
			_jsii_.MemberProperty{JsiiProperty: "typeInput", GoGetter: "TypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "updatedAt", GoGetter: "UpdatedAt"},
			_jsii_.MemberProperty{JsiiProperty: "vgwId", GoGetter: "VgwId"},
			_jsii_.MemberProperty{JsiiProperty: "vgwIdInput", GoGetter: "VgwIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "vifPeers", GoGetter: "VifPeers"},
			_jsii_.MemberProperty{JsiiProperty: "vlan", GoGetter: "Vlan"},
			_jsii_.MemberProperty{JsiiProperty: "vlanInput", GoGetter: "VlanInput"},
		},
		func() interface{} {
			j := jsiiProxy_DcVirtualInterfaceV3{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-opentelekomcloud.dcVirtualInterfaceV3.DcVirtualInterfaceV3Config",
		reflect.TypeOf((*DcVirtualInterfaceV3Config)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-opentelekomcloud.dcVirtualInterfaceV3.DcVirtualInterfaceV3VifPeers",
		reflect.TypeOf((*DcVirtualInterfaceV3VifPeers)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-opentelekomcloud.dcVirtualInterfaceV3.DcVirtualInterfaceV3VifPeersList",
		reflect.TypeOf((*DcVirtualInterfaceV3VifPeersList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "allWithMapKey", GoMethod: "AllWithMapKey"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_DcVirtualInterfaceV3VifPeersList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-opentelekomcloud.dcVirtualInterfaceV3.DcVirtualInterfaceV3VifPeersOutputReference",
		reflect.TypeOf((*DcVirtualInterfaceV3VifPeersOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "addressFamily", GoGetter: "AddressFamily"},
			_jsii_.MemberProperty{JsiiProperty: "bgpAsn", GoGetter: "BgpAsn"},
			_jsii_.MemberProperty{JsiiProperty: "bgpMd5", GoGetter: "BgpMd5"},
			_jsii_.MemberProperty{JsiiProperty: "bgpRouteLimit", GoGetter: "BgpRouteLimit"},
			_jsii_.MemberProperty{JsiiProperty: "bgpStatus", GoGetter: "BgpStatus"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "description", GoGetter: "Description"},
			_jsii_.MemberProperty{JsiiProperty: "deviceId", GoGetter: "DeviceId"},
			_jsii_.MemberProperty{JsiiProperty: "enableBfd", GoGetter: "EnableBfd"},
			_jsii_.MemberProperty{JsiiProperty: "enableNqa", GoGetter: "EnableNqa"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "localGatewayIp", GoGetter: "LocalGatewayIp"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "receiveRouteNum", GoGetter: "ReceiveRouteNum"},
			_jsii_.MemberProperty{JsiiProperty: "remoteEpGroup", GoGetter: "RemoteEpGroup"},
			_jsii_.MemberProperty{JsiiProperty: "remoteGatewayIp", GoGetter: "RemoteGatewayIp"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "routeMode", GoGetter: "RouteMode"},
			_jsii_.MemberProperty{JsiiProperty: "serviceEpGroup", GoGetter: "ServiceEpGroup"},
			_jsii_.MemberProperty{JsiiProperty: "status", GoGetter: "Status"},
			_jsii_.MemberProperty{JsiiProperty: "tenantId", GoGetter: "TenantId"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "vifId", GoGetter: "VifId"},
		},
		func() interface{} {
			j := jsiiProxy_DcVirtualInterfaceV3VifPeersOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
