package mrsclusterv1

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-opentelekomcloud.mrsClusterV1.MrsClusterV1",
		reflect.TypeOf((*MrsClusterV1)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "addJobs", GoGetter: "AddJobs"},
			_jsii_.MemberProperty{JsiiProperty: "addJobsInput", GoGetter: "AddJobsInput"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "availableZoneId", GoGetter: "AvailableZoneId"},
			_jsii_.MemberProperty{JsiiProperty: "availableZoneIdInput", GoGetter: "AvailableZoneIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "availableZoneName", GoGetter: "AvailableZoneName"},
			_jsii_.MemberProperty{JsiiProperty: "billingType", GoGetter: "BillingType"},
			_jsii_.MemberProperty{JsiiProperty: "billingTypeInput", GoGetter: "BillingTypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "bootstrapScripts", GoGetter: "BootstrapScripts"},
			_jsii_.MemberProperty{JsiiProperty: "bootstrapScriptsInput", GoGetter: "BootstrapScriptsInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "chargingStartTime", GoGetter: "ChargingStartTime"},
			_jsii_.MemberProperty{JsiiProperty: "clusterAdminSecret", GoGetter: "ClusterAdminSecret"},
			_jsii_.MemberProperty{JsiiProperty: "clusterAdminSecretInput", GoGetter: "ClusterAdminSecretInput"},
			_jsii_.MemberProperty{JsiiProperty: "clusterId", GoGetter: "ClusterId"},
			_jsii_.MemberProperty{JsiiProperty: "clusterName", GoGetter: "ClusterName"},
			_jsii_.MemberProperty{JsiiProperty: "clusterNameInput", GoGetter: "ClusterNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "clusterState", GoGetter: "ClusterState"},
			_jsii_.MemberProperty{JsiiProperty: "clusterType", GoGetter: "ClusterType"},
			_jsii_.MemberProperty{JsiiProperty: "clusterTypeInput", GoGetter: "ClusterTypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "clusterVersion", GoGetter: "ClusterVersion"},
			_jsii_.MemberProperty{JsiiProperty: "clusterVersionInput", GoGetter: "ClusterVersionInput"},
			_jsii_.MemberProperty{JsiiProperty: "componentList", GoGetter: "ComponentList"},
			_jsii_.MemberProperty{JsiiProperty: "componentListInput", GoGetter: "ComponentListInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "coreDataVolumeCount", GoGetter: "CoreDataVolumeCount"},
			_jsii_.MemberProperty{JsiiProperty: "coreDataVolumeCountInput", GoGetter: "CoreDataVolumeCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "coreDataVolumeSize", GoGetter: "CoreDataVolumeSize"},
			_jsii_.MemberProperty{JsiiProperty: "coreDataVolumeSizeInput", GoGetter: "CoreDataVolumeSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "coreDataVolumeType", GoGetter: "CoreDataVolumeType"},
			_jsii_.MemberProperty{JsiiProperty: "coreDataVolumeTypeInput", GoGetter: "CoreDataVolumeTypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "coreNodeNum", GoGetter: "CoreNodeNum"},
			_jsii_.MemberProperty{JsiiProperty: "coreNodeNumInput", GoGetter: "CoreNodeNumInput"},
			_jsii_.MemberProperty{JsiiProperty: "coreNodeProductId", GoGetter: "CoreNodeProductId"},
			_jsii_.MemberProperty{JsiiProperty: "coreNodeSize", GoGetter: "CoreNodeSize"},
			_jsii_.MemberProperty{JsiiProperty: "coreNodeSizeInput", GoGetter: "CoreNodeSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "coreNodeSpecId", GoGetter: "CoreNodeSpecId"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "createAt", GoGetter: "CreateAt"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "deploymentId", GoGetter: "DeploymentId"},
			_jsii_.MemberProperty{JsiiProperty: "duration", GoGetter: "Duration"},
			_jsii_.MemberProperty{JsiiProperty: "errorInfo", GoGetter: "ErrorInfo"},
			_jsii_.MemberProperty{JsiiProperty: "externalAlternateIp", GoGetter: "ExternalAlternateIp"},
			_jsii_.MemberProperty{JsiiProperty: "externalIp", GoGetter: "ExternalIp"},
			_jsii_.MemberProperty{JsiiProperty: "fee", GoGetter: "Fee"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "hadoopVersion", GoGetter: "HadoopVersion"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberProperty{JsiiProperty: "instanceId", GoGetter: "InstanceId"},
			_jsii_.MemberProperty{JsiiProperty: "internalIp", GoGetter: "InternalIp"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "logCollection", GoGetter: "LogCollection"},
			_jsii_.MemberProperty{JsiiProperty: "logCollectionInput", GoGetter: "LogCollectionInput"},
			_jsii_.MemberProperty{JsiiProperty: "masterDataVolumeCount", GoGetter: "MasterDataVolumeCount"},
			_jsii_.MemberProperty{JsiiProperty: "masterDataVolumeCountInput", GoGetter: "MasterDataVolumeCountInput"},
			_jsii_.MemberProperty{JsiiProperty: "masterDataVolumeSize", GoGetter: "MasterDataVolumeSize"},
			_jsii_.MemberProperty{JsiiProperty: "masterDataVolumeSizeInput", GoGetter: "MasterDataVolumeSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "masterDataVolumeType", GoGetter: "MasterDataVolumeType"},
			_jsii_.MemberProperty{JsiiProperty: "masterDataVolumeTypeInput", GoGetter: "MasterDataVolumeTypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "masterNodeIp", GoGetter: "MasterNodeIp"},
			_jsii_.MemberProperty{JsiiProperty: "masterNodeNum", GoGetter: "MasterNodeNum"},
			_jsii_.MemberProperty{JsiiProperty: "masterNodeNumInput", GoGetter: "MasterNodeNumInput"},
			_jsii_.MemberProperty{JsiiProperty: "masterNodeProductId", GoGetter: "MasterNodeProductId"},
			_jsii_.MemberProperty{JsiiProperty: "masterNodeSize", GoGetter: "MasterNodeSize"},
			_jsii_.MemberProperty{JsiiProperty: "masterNodeSizeInput", GoGetter: "MasterNodeSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "masterNodeSpecId", GoGetter: "MasterNodeSpecId"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "nodePublicCertName", GoGetter: "NodePublicCertName"},
			_jsii_.MemberProperty{JsiiProperty: "nodePublicCertNameInput", GoGetter: "NodePublicCertNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "orderId", GoGetter: "OrderId"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "privateIpFirst", GoGetter: "PrivateIpFirst"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putAddJobs", GoMethod: "PutAddJobs"},
			_jsii_.MemberMethod{JsiiMethod: "putBootstrapScripts", GoMethod: "PutBootstrapScripts"},
			_jsii_.MemberMethod{JsiiMethod: "putComponentList", GoMethod: "PutComponentList"},
			_jsii_.MemberMethod{JsiiMethod: "putTimeouts", GoMethod: "PutTimeouts"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "region", GoGetter: "Region"},
			_jsii_.MemberProperty{JsiiProperty: "regionInput", GoGetter: "RegionInput"},
			_jsii_.MemberProperty{JsiiProperty: "remark", GoGetter: "Remark"},
			_jsii_.MemberMethod{JsiiMethod: "resetAddJobs", GoMethod: "ResetAddJobs"},
			_jsii_.MemberMethod{JsiiMethod: "resetBootstrapScripts", GoMethod: "ResetBootstrapScripts"},
			_jsii_.MemberMethod{JsiiMethod: "resetClusterAdminSecret", GoMethod: "ResetClusterAdminSecret"},
			_jsii_.MemberMethod{JsiiMethod: "resetClusterType", GoMethod: "ResetClusterType"},
			_jsii_.MemberMethod{JsiiMethod: "resetCoreDataVolumeCount", GoMethod: "ResetCoreDataVolumeCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetCoreDataVolumeSize", GoMethod: "ResetCoreDataVolumeSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetCoreDataVolumeType", GoMethod: "ResetCoreDataVolumeType"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogCollection", GoMethod: "ResetLogCollection"},
			_jsii_.MemberMethod{JsiiMethod: "resetMasterDataVolumeCount", GoMethod: "ResetMasterDataVolumeCount"},
			_jsii_.MemberMethod{JsiiMethod: "resetMasterDataVolumeSize", GoMethod: "ResetMasterDataVolumeSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetMasterDataVolumeType", GoMethod: "ResetMasterDataVolumeType"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetRegion", GoMethod: "ResetRegion"},
			_jsii_.MemberMethod{JsiiMethod: "resetTags", GoMethod: "ResetTags"},
			_jsii_.MemberMethod{JsiiMethod: "resetTimeouts", GoMethod: "ResetTimeouts"},
			_jsii_.MemberMethod{JsiiMethod: "resetVolumeSize", GoMethod: "ResetVolumeSize"},
			_jsii_.MemberMethod{JsiiMethod: "resetVolumeType", GoMethod: "ResetVolumeType"},
			_jsii_.MemberProperty{JsiiProperty: "safeMode", GoGetter: "SafeMode"},
			_jsii_.MemberProperty{JsiiProperty: "safeModeInput", GoGetter: "SafeModeInput"},
			_jsii_.MemberProperty{JsiiProperty: "securityGroupsId", GoGetter: "SecurityGroupsId"},
			_jsii_.MemberProperty{JsiiProperty: "slaveSecurityGroupsId", GoGetter: "SlaveSecurityGroupsId"},
			_jsii_.MemberProperty{JsiiProperty: "subnetId", GoGetter: "SubnetId"},
			_jsii_.MemberProperty{JsiiProperty: "subnetIdInput", GoGetter: "SubnetIdInput"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "tags", GoGetter: "Tags"},
			_jsii_.MemberProperty{JsiiProperty: "tagsInput", GoGetter: "TagsInput"},
			_jsii_.MemberProperty{JsiiProperty: "tenantId", GoGetter: "TenantId"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberProperty{JsiiProperty: "timeouts", GoGetter: "Timeouts"},
			_jsii_.MemberProperty{JsiiProperty: "timeoutsInput", GoGetter: "TimeoutsInput"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "updateAt", GoGetter: "UpdateAt"},
			_jsii_.MemberProperty{JsiiProperty: "vnc", GoGetter: "Vnc"},
			_jsii_.MemberProperty{JsiiProperty: "volumeSize", GoGetter: "VolumeSize"},
			_jsii_.MemberProperty{JsiiProperty: "volumeSizeInput", GoGetter: "VolumeSizeInput"},
			_jsii_.MemberProperty{JsiiProperty: "volumeType", GoGetter: "VolumeType"},
			_jsii_.MemberProperty{JsiiProperty: "volumeTypeInput", GoGetter: "VolumeTypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "vpcId", GoGetter: "VpcId"},
			_jsii_.MemberProperty{JsiiProperty: "vpcIdInput", GoGetter: "VpcIdInput"},
		},
		func() interface{} {
			j := jsiiProxy_MrsClusterV1{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-opentelekomcloud.mrsClusterV1.MrsClusterV1AddJobs",
		reflect.TypeOf((*MrsClusterV1AddJobs)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-opentelekomcloud.mrsClusterV1.MrsClusterV1AddJobsList",
		reflect.TypeOf((*MrsClusterV1AddJobsList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_MrsClusterV1AddJobsList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-opentelekomcloud.mrsClusterV1.MrsClusterV1AddJobsOutputReference",
		reflect.TypeOf((*MrsClusterV1AddJobsOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "arguments", GoGetter: "Arguments"},
			_jsii_.MemberProperty{JsiiProperty: "argumentsInput", GoGetter: "ArgumentsInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fileAction", GoGetter: "FileAction"},
			_jsii_.MemberProperty{JsiiProperty: "fileActionInput", GoGetter: "FileActionInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "hiveScriptPath", GoGetter: "HiveScriptPath"},
			_jsii_.MemberProperty{JsiiProperty: "hiveScriptPathInput", GoGetter: "HiveScriptPathInput"},
			_jsii_.MemberProperty{JsiiProperty: "hql", GoGetter: "Hql"},
			_jsii_.MemberProperty{JsiiProperty: "hqlInput", GoGetter: "HqlInput"},
			_jsii_.MemberProperty{JsiiProperty: "input", GoGetter: "Input"},
			_jsii_.MemberProperty{JsiiProperty: "inputInput", GoGetter: "InputInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "jarPath", GoGetter: "JarPath"},
			_jsii_.MemberProperty{JsiiProperty: "jarPathInput", GoGetter: "JarPathInput"},
			_jsii_.MemberProperty{JsiiProperty: "jobLog", GoGetter: "JobLog"},
			_jsii_.MemberProperty{JsiiProperty: "jobLogInput", GoGetter: "JobLogInput"},
			_jsii_.MemberProperty{JsiiProperty: "jobName", GoGetter: "JobName"},
			_jsii_.MemberProperty{JsiiProperty: "jobNameInput", GoGetter: "JobNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "jobType", GoGetter: "JobType"},
			_jsii_.MemberProperty{JsiiProperty: "jobTypeInput", GoGetter: "JobTypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "output", GoGetter: "Output"},
			_jsii_.MemberProperty{JsiiProperty: "outputInput", GoGetter: "OutputInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetArguments", GoMethod: "ResetArguments"},
			_jsii_.MemberMethod{JsiiMethod: "resetFileAction", GoMethod: "ResetFileAction"},
			_jsii_.MemberMethod{JsiiMethod: "resetHiveScriptPath", GoMethod: "ResetHiveScriptPath"},
			_jsii_.MemberMethod{JsiiMethod: "resetHql", GoMethod: "ResetHql"},
			_jsii_.MemberMethod{JsiiMethod: "resetInput", GoMethod: "ResetInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetJobLog", GoMethod: "ResetJobLog"},
			_jsii_.MemberMethod{JsiiMethod: "resetOutput", GoMethod: "ResetOutput"},
			_jsii_.MemberMethod{JsiiMethod: "resetShutdownCluster", GoMethod: "ResetShutdownCluster"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "shutdownCluster", GoGetter: "ShutdownCluster"},
			_jsii_.MemberProperty{JsiiProperty: "shutdownClusterInput", GoGetter: "ShutdownClusterInput"},
			_jsii_.MemberProperty{JsiiProperty: "submitJobOnceClusterRun", GoGetter: "SubmitJobOnceClusterRun"},
			_jsii_.MemberProperty{JsiiProperty: "submitJobOnceClusterRunInput", GoGetter: "SubmitJobOnceClusterRunInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_MrsClusterV1AddJobsOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-opentelekomcloud.mrsClusterV1.MrsClusterV1BootstrapScripts",
		reflect.TypeOf((*MrsClusterV1BootstrapScripts)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-opentelekomcloud.mrsClusterV1.MrsClusterV1BootstrapScriptsList",
		reflect.TypeOf((*MrsClusterV1BootstrapScriptsList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_MrsClusterV1BootstrapScriptsList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-opentelekomcloud.mrsClusterV1.MrsClusterV1BootstrapScriptsOutputReference",
		reflect.TypeOf((*MrsClusterV1BootstrapScriptsOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "activeMaster", GoGetter: "ActiveMaster"},
			_jsii_.MemberProperty{JsiiProperty: "activeMasterInput", GoGetter: "ActiveMasterInput"},
			_jsii_.MemberProperty{JsiiProperty: "beforeComponentStart", GoGetter: "BeforeComponentStart"},
			_jsii_.MemberProperty{JsiiProperty: "beforeComponentStartInput", GoGetter: "BeforeComponentStartInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "failAction", GoGetter: "FailAction"},
			_jsii_.MemberProperty{JsiiProperty: "failActionInput", GoGetter: "FailActionInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "nodes", GoGetter: "Nodes"},
			_jsii_.MemberProperty{JsiiProperty: "nodesInput", GoGetter: "NodesInput"},
			_jsii_.MemberProperty{JsiiProperty: "parameters", GoGetter: "Parameters"},
			_jsii_.MemberProperty{JsiiProperty: "parametersInput", GoGetter: "ParametersInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetActiveMaster", GoMethod: "ResetActiveMaster"},
			_jsii_.MemberMethod{JsiiMethod: "resetBeforeComponentStart", GoMethod: "ResetBeforeComponentStart"},
			_jsii_.MemberMethod{JsiiMethod: "resetParameters", GoMethod: "ResetParameters"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "uri", GoGetter: "Uri"},
			_jsii_.MemberProperty{JsiiProperty: "uriInput", GoGetter: "UriInput"},
		},
		func() interface{} {
			j := jsiiProxy_MrsClusterV1BootstrapScriptsOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-opentelekomcloud.mrsClusterV1.MrsClusterV1ComponentList",
		reflect.TypeOf((*MrsClusterV1ComponentList)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-opentelekomcloud.mrsClusterV1.MrsClusterV1ComponentListList",
		reflect.TypeOf((*MrsClusterV1ComponentListList)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "get", GoMethod: "Get"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "wrapsSet", GoGetter: "WrapsSet"},
		},
		func() interface{} {
			j := jsiiProxy_MrsClusterV1ComponentListList{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexList)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-opentelekomcloud.mrsClusterV1.MrsClusterV1ComponentListOutputReference",
		reflect.TypeOf((*MrsClusterV1ComponentListOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberProperty{JsiiProperty: "componentDesc", GoGetter: "ComponentDesc"},
			_jsii_.MemberProperty{JsiiProperty: "componentId", GoGetter: "ComponentId"},
			_jsii_.MemberProperty{JsiiProperty: "componentName", GoGetter: "ComponentName"},
			_jsii_.MemberProperty{JsiiProperty: "componentNameInput", GoGetter: "ComponentNameInput"},
			_jsii_.MemberProperty{JsiiProperty: "componentVersion", GoGetter: "ComponentVersion"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_MrsClusterV1ComponentListOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-opentelekomcloud.mrsClusterV1.MrsClusterV1Config",
		reflect.TypeOf((*MrsClusterV1Config)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-opentelekomcloud.mrsClusterV1.MrsClusterV1Timeouts",
		reflect.TypeOf((*MrsClusterV1Timeouts)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-opentelekomcloud.mrsClusterV1.MrsClusterV1TimeoutsOutputReference",
		reflect.TypeOf((*MrsClusterV1TimeoutsOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "create", GoGetter: "Create"},
			_jsii_.MemberProperty{JsiiProperty: "createInput", GoGetter: "CreateInput"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "delete", GoGetter: "Delete"},
			_jsii_.MemberProperty{JsiiProperty: "deleteInput", GoGetter: "DeleteInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resetCreate", GoMethod: "ResetCreate"},
			_jsii_.MemberMethod{JsiiMethod: "resetDelete", GoMethod: "ResetDelete"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_MrsClusterV1TimeoutsOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
}
