// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package dataopentelekomcloudimagesimagev2

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-opentelekomcloud.dataOpentelekomcloudImagesImageV2.DataOpentelekomcloudImagesImageV2",
		reflect.TypeOf((*DataOpentelekomcloudImagesImageV2)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "backupId", GoGetter: "BackupId"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "checksum", GoGetter: "Checksum"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "containerFormat", GoGetter: "ContainerFormat"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "createdAt", GoGetter: "CreatedAt"},
			_jsii_.MemberProperty{JsiiProperty: "dataOrigin", GoGetter: "DataOrigin"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "description", GoGetter: "Description"},
			_jsii_.MemberProperty{JsiiProperty: "diskFormat", GoGetter: "DiskFormat"},
			_jsii_.MemberProperty{JsiiProperty: "file", GoGetter: "File"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "imageSourceType", GoGetter: "ImageSourceType"},
			_jsii_.MemberProperty{JsiiProperty: "imageType", GoGetter: "ImageType"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "isRegistered", GoGetter: "IsRegistered"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "loginUser", GoGetter: "LoginUser"},
			_jsii_.MemberProperty{JsiiProperty: "minDisk", GoGetter: "MinDisk"},
			_jsii_.MemberProperty{JsiiProperty: "minRam", GoGetter: "MinRam"},
			_jsii_.MemberProperty{JsiiProperty: "mostRecent", GoGetter: "MostRecent"},
			_jsii_.MemberProperty{JsiiProperty: "mostRecentInput", GoGetter: "MostRecentInput"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "nameRegex", GoGetter: "NameRegex"},
			_jsii_.MemberProperty{JsiiProperty: "nameRegexInput", GoGetter: "NameRegexInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberProperty{JsiiProperty: "originalImageName", GoGetter: "OriginalImageName"},
			_jsii_.MemberProperty{JsiiProperty: "osBit", GoGetter: "OsBit"},
			_jsii_.MemberProperty{JsiiProperty: "osType", GoGetter: "OsType"},
			_jsii_.MemberProperty{JsiiProperty: "osVersion", GoGetter: "OsVersion"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "owner", GoGetter: "Owner"},
			_jsii_.MemberProperty{JsiiProperty: "ownerInput", GoGetter: "OwnerInput"},
			_jsii_.MemberProperty{JsiiProperty: "platform", GoGetter: "Platform"},
			_jsii_.MemberProperty{JsiiProperty: "protected", GoGetter: "Protected"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberMethod{JsiiMethod: "resetMostRecent", GoMethod: "ResetMostRecent"},
			_jsii_.MemberMethod{JsiiMethod: "resetName", GoMethod: "ResetName"},
			_jsii_.MemberMethod{JsiiMethod: "resetNameRegex", GoMethod: "ResetNameRegex"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetOwner", GoMethod: "ResetOwner"},
			_jsii_.MemberMethod{JsiiMethod: "resetSizeMax", GoMethod: "ResetSizeMax"},
			_jsii_.MemberMethod{JsiiMethod: "resetSizeMin", GoMethod: "ResetSizeMin"},
			_jsii_.MemberMethod{JsiiMethod: "resetSortDirection", GoMethod: "ResetSortDirection"},
			_jsii_.MemberMethod{JsiiMethod: "resetSortKey", GoMethod: "ResetSortKey"},
			_jsii_.MemberMethod{JsiiMethod: "resetTag", GoMethod: "ResetTag"},
			_jsii_.MemberMethod{JsiiMethod: "resetVisibility", GoMethod: "ResetVisibility"},
			_jsii_.MemberProperty{JsiiProperty: "schema", GoGetter: "Schema"},
			_jsii_.MemberProperty{JsiiProperty: "sizeBytes", GoGetter: "SizeBytes"},
			_jsii_.MemberProperty{JsiiProperty: "sizeMax", GoGetter: "SizeMax"},
			_jsii_.MemberProperty{JsiiProperty: "sizeMaxInput", GoGetter: "SizeMaxInput"},
			_jsii_.MemberProperty{JsiiProperty: "sizeMin", GoGetter: "SizeMin"},
			_jsii_.MemberProperty{JsiiProperty: "sizeMinInput", GoGetter: "SizeMinInput"},
			_jsii_.MemberProperty{JsiiProperty: "sortDirection", GoGetter: "SortDirection"},
			_jsii_.MemberProperty{JsiiProperty: "sortDirectionInput", GoGetter: "SortDirectionInput"},
			_jsii_.MemberProperty{JsiiProperty: "sortKey", GoGetter: "SortKey"},
			_jsii_.MemberProperty{JsiiProperty: "sortKeyInput", GoGetter: "SortKeyInput"},
			_jsii_.MemberProperty{JsiiProperty: "status", GoGetter: "Status"},
			_jsii_.MemberProperty{JsiiProperty: "supportDiskIntensive", GoGetter: "SupportDiskIntensive"},
			_jsii_.MemberProperty{JsiiProperty: "supportHighPerformance", GoGetter: "SupportHighPerformance"},
			_jsii_.MemberProperty{JsiiProperty: "supportKvm", GoGetter: "SupportKvm"},
			_jsii_.MemberProperty{JsiiProperty: "supportKvmGpuType", GoGetter: "SupportKvmGpuType"},
			_jsii_.MemberProperty{JsiiProperty: "supportKvmInfiniband", GoGetter: "SupportKvmInfiniband"},
			_jsii_.MemberProperty{JsiiProperty: "supportLargeMemory", GoGetter: "SupportLargeMemory"},
			_jsii_.MemberProperty{JsiiProperty: "supportXen", GoGetter: "SupportXen"},
			_jsii_.MemberProperty{JsiiProperty: "supportXenGpuType", GoGetter: "SupportXenGpuType"},
			_jsii_.MemberProperty{JsiiProperty: "supportXenHana", GoGetter: "SupportXenHana"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "systemCmkId", GoGetter: "SystemCmkId"},
			_jsii_.MemberProperty{JsiiProperty: "tag", GoGetter: "Tag"},
			_jsii_.MemberProperty{JsiiProperty: "tagInput", GoGetter: "TagInput"},
			_jsii_.MemberProperty{JsiiProperty: "tags", GoGetter: "Tags"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
			_jsii_.MemberProperty{JsiiProperty: "updatedAt", GoGetter: "UpdatedAt"},
			_jsii_.MemberProperty{JsiiProperty: "virtualEnvType", GoGetter: "VirtualEnvType"},
			_jsii_.MemberProperty{JsiiProperty: "visibility", GoGetter: "Visibility"},
			_jsii_.MemberProperty{JsiiProperty: "visibilityInput", GoGetter: "VisibilityInput"},
		},
		func() interface{} {
			j := jsiiProxy_DataOpentelekomcloudImagesImageV2{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformDataSource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-opentelekomcloud.dataOpentelekomcloudImagesImageV2.DataOpentelekomcloudImagesImageV2Config",
		reflect.TypeOf((*DataOpentelekomcloudImagesImageV2Config)(nil)).Elem(),
	)
}
