// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: MPL-2.0

package ltscceaccessv3

import (
	"reflect"

	_jsii_ "github.com/aws/jsii-runtime-go/runtime"
)

func init() {
	_jsii_.RegisterClass(
		"@cdktf/provider-opentelekomcloud.ltsCceAccessV3.LtsCceAccessV3",
		reflect.TypeOf((*LtsCceAccessV3)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "accessConfig", GoGetter: "AccessConfig"},
			_jsii_.MemberProperty{JsiiProperty: "accessConfigInput", GoGetter: "AccessConfigInput"},
			_jsii_.MemberProperty{JsiiProperty: "accessType", GoGetter: "AccessType"},
			_jsii_.MemberMethod{JsiiMethod: "addMoveTarget", GoMethod: "AddMoveTarget"},
			_jsii_.MemberMethod{JsiiMethod: "addOverride", GoMethod: "AddOverride"},
			_jsii_.MemberProperty{JsiiProperty: "binaryCollect", GoGetter: "BinaryCollect"},
			_jsii_.MemberProperty{JsiiProperty: "binaryCollectInput", GoGetter: "BinaryCollectInput"},
			_jsii_.MemberProperty{JsiiProperty: "cdktfStack", GoGetter: "CdktfStack"},
			_jsii_.MemberProperty{JsiiProperty: "clusterId", GoGetter: "ClusterId"},
			_jsii_.MemberProperty{JsiiProperty: "clusterIdInput", GoGetter: "ClusterIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "connection", GoGetter: "Connection"},
			_jsii_.MemberProperty{JsiiProperty: "constructNodeMetadata", GoGetter: "ConstructNodeMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "count", GoGetter: "Count"},
			_jsii_.MemberProperty{JsiiProperty: "createdAt", GoGetter: "CreatedAt"},
			_jsii_.MemberProperty{JsiiProperty: "dependsOn", GoGetter: "DependsOn"},
			_jsii_.MemberProperty{JsiiProperty: "forEach", GoGetter: "ForEach"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberProperty{JsiiProperty: "friendlyUniqueId", GoGetter: "FriendlyUniqueId"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "hasResourceMove", GoMethod: "HasResourceMove"},
			_jsii_.MemberProperty{JsiiProperty: "hostGroupIds", GoGetter: "HostGroupIds"},
			_jsii_.MemberProperty{JsiiProperty: "hostGroupIdsInput", GoGetter: "HostGroupIdsInput"},
			_jsii_.MemberProperty{JsiiProperty: "id", GoGetter: "Id"},
			_jsii_.MemberProperty{JsiiProperty: "idInput", GoGetter: "IdInput"},
			_jsii_.MemberMethod{JsiiMethod: "importFrom", GoMethod: "ImportFrom"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "lifecycle", GoGetter: "Lifecycle"},
			_jsii_.MemberProperty{JsiiProperty: "logGroupId", GoGetter: "LogGroupId"},
			_jsii_.MemberProperty{JsiiProperty: "logGroupIdInput", GoGetter: "LogGroupIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "logGroupName", GoGetter: "LogGroupName"},
			_jsii_.MemberProperty{JsiiProperty: "logSplit", GoGetter: "LogSplit"},
			_jsii_.MemberProperty{JsiiProperty: "logSplitInput", GoGetter: "LogSplitInput"},
			_jsii_.MemberProperty{JsiiProperty: "logStreamId", GoGetter: "LogStreamId"},
			_jsii_.MemberProperty{JsiiProperty: "logStreamIdInput", GoGetter: "LogStreamIdInput"},
			_jsii_.MemberProperty{JsiiProperty: "logStreamName", GoGetter: "LogStreamName"},
			_jsii_.MemberMethod{JsiiMethod: "moveFromId", GoMethod: "MoveFromId"},
			_jsii_.MemberMethod{JsiiMethod: "moveTo", GoMethod: "MoveTo"},
			_jsii_.MemberMethod{JsiiMethod: "moveToId", GoMethod: "MoveToId"},
			_jsii_.MemberProperty{JsiiProperty: "name", GoGetter: "Name"},
			_jsii_.MemberProperty{JsiiProperty: "nameInput", GoGetter: "NameInput"},
			_jsii_.MemberProperty{JsiiProperty: "node", GoGetter: "Node"},
			_jsii_.MemberMethod{JsiiMethod: "overrideLogicalId", GoMethod: "OverrideLogicalId"},
			_jsii_.MemberProperty{JsiiProperty: "provider", GoGetter: "Provider"},
			_jsii_.MemberProperty{JsiiProperty: "provisioners", GoGetter: "Provisioners"},
			_jsii_.MemberMethod{JsiiMethod: "putAccessConfig", GoMethod: "PutAccessConfig"},
			_jsii_.MemberProperty{JsiiProperty: "rawOverrides", GoGetter: "RawOverrides"},
			_jsii_.MemberProperty{JsiiProperty: "region", GoGetter: "Region"},
			_jsii_.MemberMethod{JsiiMethod: "resetBinaryCollect", GoMethod: "ResetBinaryCollect"},
			_jsii_.MemberMethod{JsiiMethod: "resetHostGroupIds", GoMethod: "ResetHostGroupIds"},
			_jsii_.MemberMethod{JsiiMethod: "resetId", GoMethod: "ResetId"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogSplit", GoMethod: "ResetLogSplit"},
			_jsii_.MemberMethod{JsiiMethod: "resetOverrideLogicalId", GoMethod: "ResetOverrideLogicalId"},
			_jsii_.MemberMethod{JsiiMethod: "resetTags", GoMethod: "ResetTags"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeAttributes", GoMethod: "SynthesizeAttributes"},
			_jsii_.MemberMethod{JsiiMethod: "synthesizeHclAttributes", GoMethod: "SynthesizeHclAttributes"},
			_jsii_.MemberProperty{JsiiProperty: "tags", GoGetter: "Tags"},
			_jsii_.MemberProperty{JsiiProperty: "tagsInput", GoGetter: "TagsInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformGeneratorMetadata", GoGetter: "TerraformGeneratorMetadata"},
			_jsii_.MemberProperty{JsiiProperty: "terraformMetaArguments", GoGetter: "TerraformMetaArguments"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResourceType", GoGetter: "TerraformResourceType"},
			_jsii_.MemberMethod{JsiiMethod: "toHclTerraform", GoMethod: "ToHclTerraform"},
			_jsii_.MemberMethod{JsiiMethod: "toMetadata", GoMethod: "ToMetadata"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberMethod{JsiiMethod: "toTerraform", GoMethod: "ToTerraform"},
		},
		func() interface{} {
			j := jsiiProxy_LtsCceAccessV3{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfTerraformResource)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-opentelekomcloud.ltsCceAccessV3.LtsCceAccessV3AccessConfig",
		reflect.TypeOf((*LtsCceAccessV3AccessConfig)(nil)).Elem(),
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-opentelekomcloud.ltsCceAccessV3.LtsCceAccessV3AccessConfigMultiLogFormat",
		reflect.TypeOf((*LtsCceAccessV3AccessConfigMultiLogFormat)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-opentelekomcloud.ltsCceAccessV3.LtsCceAccessV3AccessConfigMultiLogFormatOutputReference",
		reflect.TypeOf((*LtsCceAccessV3AccessConfigMultiLogFormatOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "mode", GoGetter: "Mode"},
			_jsii_.MemberProperty{JsiiProperty: "modeInput", GoGetter: "ModeInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetValue", GoMethod: "ResetValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "value", GoGetter: "Value"},
			_jsii_.MemberProperty{JsiiProperty: "valueInput", GoGetter: "ValueInput"},
		},
		func() interface{} {
			j := jsiiProxy_LtsCceAccessV3AccessConfigMultiLogFormatOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-opentelekomcloud.ltsCceAccessV3.LtsCceAccessV3AccessConfigOutputReference",
		reflect.TypeOf((*LtsCceAccessV3AccessConfigOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "blackPaths", GoGetter: "BlackPaths"},
			_jsii_.MemberProperty{JsiiProperty: "blackPathsInput", GoGetter: "BlackPathsInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "containerNameRegex", GoGetter: "ContainerNameRegex"},
			_jsii_.MemberProperty{JsiiProperty: "containerNameRegexInput", GoGetter: "ContainerNameRegexInput"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "excludeEnvs", GoGetter: "ExcludeEnvs"},
			_jsii_.MemberProperty{JsiiProperty: "excludeEnvsInput", GoGetter: "ExcludeEnvsInput"},
			_jsii_.MemberProperty{JsiiProperty: "excludeK8SLabels", GoGetter: "ExcludeK8SLabels"},
			_jsii_.MemberProperty{JsiiProperty: "excludeK8SLabelsInput", GoGetter: "ExcludeK8SLabelsInput"},
			_jsii_.MemberProperty{JsiiProperty: "excludeLabels", GoGetter: "ExcludeLabels"},
			_jsii_.MemberProperty{JsiiProperty: "excludeLabelsInput", GoGetter: "ExcludeLabelsInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "includeEnvs", GoGetter: "IncludeEnvs"},
			_jsii_.MemberProperty{JsiiProperty: "includeEnvsInput", GoGetter: "IncludeEnvsInput"},
			_jsii_.MemberProperty{JsiiProperty: "includeK8SLabels", GoGetter: "IncludeK8SLabels"},
			_jsii_.MemberProperty{JsiiProperty: "includeK8SLabelsInput", GoGetter: "IncludeK8SLabelsInput"},
			_jsii_.MemberProperty{JsiiProperty: "includeLabels", GoGetter: "IncludeLabels"},
			_jsii_.MemberProperty{JsiiProperty: "includeLabelsInput", GoGetter: "IncludeLabelsInput"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "logEnvs", GoGetter: "LogEnvs"},
			_jsii_.MemberProperty{JsiiProperty: "logEnvsInput", GoGetter: "LogEnvsInput"},
			_jsii_.MemberProperty{JsiiProperty: "logK8S", GoGetter: "LogK8S"},
			_jsii_.MemberProperty{JsiiProperty: "logK8SInput", GoGetter: "LogK8SInput"},
			_jsii_.MemberProperty{JsiiProperty: "logLabels", GoGetter: "LogLabels"},
			_jsii_.MemberProperty{JsiiProperty: "logLabelsInput", GoGetter: "LogLabelsInput"},
			_jsii_.MemberProperty{JsiiProperty: "multiLogFormat", GoGetter: "MultiLogFormat"},
			_jsii_.MemberProperty{JsiiProperty: "multiLogFormatInput", GoGetter: "MultiLogFormatInput"},
			_jsii_.MemberProperty{JsiiProperty: "nameSpaceRegex", GoGetter: "NameSpaceRegex"},
			_jsii_.MemberProperty{JsiiProperty: "nameSpaceRegexInput", GoGetter: "NameSpaceRegexInput"},
			_jsii_.MemberProperty{JsiiProperty: "paths", GoGetter: "Paths"},
			_jsii_.MemberProperty{JsiiProperty: "pathsInput", GoGetter: "PathsInput"},
			_jsii_.MemberProperty{JsiiProperty: "pathType", GoGetter: "PathType"},
			_jsii_.MemberProperty{JsiiProperty: "pathTypeInput", GoGetter: "PathTypeInput"},
			_jsii_.MemberProperty{JsiiProperty: "podNameRegex", GoGetter: "PodNameRegex"},
			_jsii_.MemberProperty{JsiiProperty: "podNameRegexInput", GoGetter: "PodNameRegexInput"},
			_jsii_.MemberMethod{JsiiMethod: "putMultiLogFormat", GoMethod: "PutMultiLogFormat"},
			_jsii_.MemberMethod{JsiiMethod: "putSingleLogFormat", GoMethod: "PutSingleLogFormat"},
			_jsii_.MemberMethod{JsiiMethod: "putWindowsLogInfo", GoMethod: "PutWindowsLogInfo"},
			_jsii_.MemberMethod{JsiiMethod: "resetBlackPaths", GoMethod: "ResetBlackPaths"},
			_jsii_.MemberMethod{JsiiMethod: "resetContainerNameRegex", GoMethod: "ResetContainerNameRegex"},
			_jsii_.MemberMethod{JsiiMethod: "resetExcludeEnvs", GoMethod: "ResetExcludeEnvs"},
			_jsii_.MemberMethod{JsiiMethod: "resetExcludeK8SLabels", GoMethod: "ResetExcludeK8SLabels"},
			_jsii_.MemberMethod{JsiiMethod: "resetExcludeLabels", GoMethod: "ResetExcludeLabels"},
			_jsii_.MemberMethod{JsiiMethod: "resetIncludeEnvs", GoMethod: "ResetIncludeEnvs"},
			_jsii_.MemberMethod{JsiiMethod: "resetIncludeK8SLabels", GoMethod: "ResetIncludeK8SLabels"},
			_jsii_.MemberMethod{JsiiMethod: "resetIncludeLabels", GoMethod: "ResetIncludeLabels"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogEnvs", GoMethod: "ResetLogEnvs"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogK8S", GoMethod: "ResetLogK8S"},
			_jsii_.MemberMethod{JsiiMethod: "resetLogLabels", GoMethod: "ResetLogLabels"},
			_jsii_.MemberMethod{JsiiMethod: "resetMultiLogFormat", GoMethod: "ResetMultiLogFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetNameSpaceRegex", GoMethod: "ResetNameSpaceRegex"},
			_jsii_.MemberMethod{JsiiMethod: "resetPaths", GoMethod: "ResetPaths"},
			_jsii_.MemberMethod{JsiiMethod: "resetPodNameRegex", GoMethod: "ResetPodNameRegex"},
			_jsii_.MemberMethod{JsiiMethod: "resetSingleLogFormat", GoMethod: "ResetSingleLogFormat"},
			_jsii_.MemberMethod{JsiiMethod: "resetStderr", GoMethod: "ResetStderr"},
			_jsii_.MemberMethod{JsiiMethod: "resetStdout", GoMethod: "ResetStdout"},
			_jsii_.MemberMethod{JsiiMethod: "resetWindowsLogInfo", GoMethod: "ResetWindowsLogInfo"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "singleLogFormat", GoGetter: "SingleLogFormat"},
			_jsii_.MemberProperty{JsiiProperty: "singleLogFormatInput", GoGetter: "SingleLogFormatInput"},
			_jsii_.MemberProperty{JsiiProperty: "stderr", GoGetter: "Stderr"},
			_jsii_.MemberProperty{JsiiProperty: "stderrInput", GoGetter: "StderrInput"},
			_jsii_.MemberProperty{JsiiProperty: "stdout", GoGetter: "Stdout"},
			_jsii_.MemberProperty{JsiiProperty: "stdoutInput", GoGetter: "StdoutInput"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "windowsLogInfo", GoGetter: "WindowsLogInfo"},
			_jsii_.MemberProperty{JsiiProperty: "windowsLogInfoInput", GoGetter: "WindowsLogInfoInput"},
		},
		func() interface{} {
			j := jsiiProxy_LtsCceAccessV3AccessConfigOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-opentelekomcloud.ltsCceAccessV3.LtsCceAccessV3AccessConfigSingleLogFormat",
		reflect.TypeOf((*LtsCceAccessV3AccessConfigSingleLogFormat)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-opentelekomcloud.ltsCceAccessV3.LtsCceAccessV3AccessConfigSingleLogFormatOutputReference",
		reflect.TypeOf((*LtsCceAccessV3AccessConfigSingleLogFormatOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "mode", GoGetter: "Mode"},
			_jsii_.MemberProperty{JsiiProperty: "modeInput", GoGetter: "ModeInput"},
			_jsii_.MemberMethod{JsiiMethod: "resetValue", GoMethod: "ResetValue"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
			_jsii_.MemberProperty{JsiiProperty: "value", GoGetter: "Value"},
			_jsii_.MemberProperty{JsiiProperty: "valueInput", GoGetter: "ValueInput"},
		},
		func() interface{} {
			j := jsiiProxy_LtsCceAccessV3AccessConfigSingleLogFormatOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-opentelekomcloud.ltsCceAccessV3.LtsCceAccessV3AccessConfigWindowsLogInfo",
		reflect.TypeOf((*LtsCceAccessV3AccessConfigWindowsLogInfo)(nil)).Elem(),
	)
	_jsii_.RegisterClass(
		"@cdktf/provider-opentelekomcloud.ltsCceAccessV3.LtsCceAccessV3AccessConfigWindowsLogInfoOutputReference",
		reflect.TypeOf((*LtsCceAccessV3AccessConfigWindowsLogInfoOutputReference)(nil)).Elem(),
		[]_jsii_.Member{
			_jsii_.MemberProperty{JsiiProperty: "categories", GoGetter: "Categories"},
			_jsii_.MemberProperty{JsiiProperty: "categoriesInput", GoGetter: "CategoriesInput"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIndex", GoGetter: "ComplexObjectIndex"},
			_jsii_.MemberProperty{JsiiProperty: "complexObjectIsFromSet", GoGetter: "ComplexObjectIsFromSet"},
			_jsii_.MemberMethod{JsiiMethod: "computeFqn", GoMethod: "ComputeFqn"},
			_jsii_.MemberProperty{JsiiProperty: "creationStack", GoGetter: "CreationStack"},
			_jsii_.MemberProperty{JsiiProperty: "eventLevel", GoGetter: "EventLevel"},
			_jsii_.MemberProperty{JsiiProperty: "eventLevelInput", GoGetter: "EventLevelInput"},
			_jsii_.MemberProperty{JsiiProperty: "fqn", GoGetter: "Fqn"},
			_jsii_.MemberMethod{JsiiMethod: "getAnyMapAttribute", GoMethod: "GetAnyMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanAttribute", GoMethod: "GetBooleanAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getBooleanMapAttribute", GoMethod: "GetBooleanMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getListAttribute", GoMethod: "GetListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberAttribute", GoMethod: "GetNumberAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberListAttribute", GoMethod: "GetNumberListAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getNumberMapAttribute", GoMethod: "GetNumberMapAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringAttribute", GoMethod: "GetStringAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "getStringMapAttribute", GoMethod: "GetStringMapAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "internalValue", GoGetter: "InternalValue"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationAsList", GoMethod: "InterpolationAsList"},
			_jsii_.MemberMethod{JsiiMethod: "interpolationForAttribute", GoMethod: "InterpolationForAttribute"},
			_jsii_.MemberMethod{JsiiMethod: "resolve", GoMethod: "Resolve"},
			_jsii_.MemberProperty{JsiiProperty: "terraformAttribute", GoGetter: "TerraformAttribute"},
			_jsii_.MemberProperty{JsiiProperty: "terraformResource", GoGetter: "TerraformResource"},
			_jsii_.MemberProperty{JsiiProperty: "timeOffset", GoGetter: "TimeOffset"},
			_jsii_.MemberProperty{JsiiProperty: "timeOffsetInput", GoGetter: "TimeOffsetInput"},
			_jsii_.MemberProperty{JsiiProperty: "timeOffsetUnit", GoGetter: "TimeOffsetUnit"},
			_jsii_.MemberProperty{JsiiProperty: "timeOffsetUnitInput", GoGetter: "TimeOffsetUnitInput"},
			_jsii_.MemberMethod{JsiiMethod: "toString", GoMethod: "ToString"},
		},
		func() interface{} {
			j := jsiiProxy_LtsCceAccessV3AccessConfigWindowsLogInfoOutputReference{}
			_jsii_.InitJsiiProxy(&j.Type__cdktfComplexObject)
			return &j
		},
	)
	_jsii_.RegisterStruct(
		"@cdktf/provider-opentelekomcloud.ltsCceAccessV3.LtsCceAccessV3Config",
		reflect.TypeOf((*LtsCceAccessV3Config)(nil)).Elem(),
	)
}
